name: EAS Build

on:
  # Trigger automático quando fizer push para estas branches
  push:
    branches:
      - main
      - master
      - production
      - release/*

  # Permite executar manualmente pelo GitHub Actions UI
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build'
        required: true
        default: 'all'
        type: choice
        options:
          - ios
          - android
          - all
      profile:
        description: 'Build profile'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - preview
          - development

jobs:
  build:
    name: EAS Build - ${{ github.event.inputs.platform || 'all' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Instalar dependências
        run: npm ci

      - name: Build iOS
        if: ${{ github.event.inputs.platform == 'ios' || github.event.inputs.platform == 'all' || github.event.inputs.platform == '' }}
        run: eas build --platform ios --profile ${{ github.event.inputs.profile || 'production' }} --non-interactive --no-wait

      - name: Build Android
        if: ${{ github.event.inputs.platform == 'android' || github.event.inputs.platform == 'all' || github.event.inputs.platform == '' }}
        run: eas build --platform android --profile ${{ github.event.inputs.profile || 'production' }} --non-interactive --no-wait

      - name: Comentário de sucesso
        if: success()
        run: |
          echo "✅ Build iniciado com sucesso!"
          echo "📱 Acompanhe o progresso em: https://expo.dev/accounts/ailun/projects/ailun-saude/builds"
